version: '2'

services:
  node:
    build: .
    image: htdise:latest
    restart: "no"
    command: /usr/local/bin/test -n 5 -mc 4 -t 5
    scale: 5
    build: .
    networks:
      dise-net:

networks:
  dise-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
