version: '2'

services:
  client:
    build: .
    image: gabrielkulp/htdise
    restart: "no"
    command: /usr/local/bin/test -n "${SERVER_COUNT:-9}" -mf "${THRESHOLD_FRACTION:-0.7}" -t "${TRIAL_SIZE:-4096}" -client
    networks:
      dise-net:
        ipv4_address: 10.0.0.2

  server:
    build: .
    image: gabrielkulp/htdise
    restart: "no"
    command: /usr/local/bin/test -n "${SERVER_COUNT:-9}"
    deploy:
      replicas: "${SERVER_COUNT:-9}"
    networks:
      dise-net:

networks:
  dise-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
