version: '2'

services:
  node:
    build: .
    image: gabrielkulp/htdise:latest
    restart: "no"
    command: /usr/local/bin/test -n "${NODE_COUNT:-10}" -mf "${THRESHOLD_FRACTION:-0.7}" -t "${TRIAL_SIZE:-4096}"
    deploy:
      replicas: "${NODE_COUNT:-10}"
    build: .
    networks:
      dise-net:

networks:
  dise-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
