version: '2'

services:
  node:
    build: .
    image: gabrielkulp/htdise:latest
    restart: "no"
    command: /usr/local/bin/test -n 10 -mc ${MC} -t 4
    scale: 10
    networks:
      dise-net:
#        ipv4_address: 10.0.10.0

networks:
  dise-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
