version: '2'

services:
  client:
    build: .
    image: gabrielkulp/htdise:latest
    command: bin/test -n "${SERVER_COUNT:-9}" -mf "${THRESHOLD_FRACTION:-0.7}" -t "${TRIAL_SIZE:-4096}" -client
    depends_on:
      - uptime
    networks:
      dise-net:
        ipv4_address: 10.0.0.2

  server:
    build: .
    image: gabrielkulp/htdise:latest
    command: bin/restart.py "${SERVER_COUNT:-9}" "${THRESHOLD_FRACTION:-0.7}" 60 30
    depends_on:
      - uptime
    deploy:
      replicas: "${SERVER_COUNT:-9}"
    networks:
      dise-net:

  uptime:
    build: .
    image: gabrielkulp/htdise:latest
    command: bin/uptime_server.py "${SERVER_COUNT:-9}" 
    networks:
      dise-net:
        ipv4_address: 10.0.0.254

networks:
  dise-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
