version: '2'

services:
  node:
    build: .
    image: htdise:latest
    restart: "no"
    command: /usr/local/bin/test -n 25 -mf .7 -t 8192
    deploy:
      replicas: 25
    build: .
    networks:
      dise-net:

networks:
  dise-net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
